# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=200)),
                ('venue', models.CharField(default='', max_length=50)),
                ('st_time', models.IntegerField(default=0)),
                ('minutes_duration', models.IntegerField(default=0)),
                ('age_suitability', models.IntegerField(default=0)),
                ('group', models.CharField(default='', max_length=50)),
                ('wheelchair_acc', models.BooleanField(default=True)),
                ('level_acc', models.BooleanField(default=True)),
                ('disabled_toilets', models.BooleanField(default=True)),
                ('hearing_loop', models.BooleanField(default=True)),
            ],
        ),
    ]
