# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.CharField(default='0000', max_length=4, primary_key=True, serialize=False)),
                ('showName', models.CharField(default='', max_length=30)),
                ('generalGenre', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('suitability', models.IntegerField(default=0)),
                ('minutesDuration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Date_Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(default='0000', max_length=4)),
                ('date', models.CharField(default='', max_length=30)),
                ('venueID', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueID', models.CharField(default='0000', max_length=4, primary_key=True, serialize=False)),
                ('location', models.CharField(default='', max_length=30)),
                ('wheelchair_acc', models.BooleanField(default=True)),
                ('level_acc', models.BooleanField(default=True)),
                ('disabled_toilets', models.BooleanField(default=True)),
                ('hearing_loop', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Harry',
        ),
    ]
