# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0002_auto_20160607_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='generalGenre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='showName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event_date_venue',
            name='venueID',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
